[package]
name = "http-server-rust"
version = "0.1.0"
authors = ["Saahil Bhavsar <saahil_bhavsar@outlook.com>"]
edition = "2021"

[dependencies]
flate2 = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.3.0"
